### ISSUE TITLE
Question about DCNv2_pytorch1 

### ISSUE THREAD

**Issue by zdaiot** [lj1995-computer-vision/Trident-Dehazing-Network#1]
Hello, when I use Pytorch1.5, there is a problem with compiling DCNv2_pytorch1 as follows：

```bash
(base) $ python build.py
which: no hipcc in (/data4/zhaodali/anaconda/bin:/data4/zhaodali/usr/GCC-5.5.0/bin:/data4/zhaodali/anaconda3/bin:/data4/zhaodali/anaconda3/condabin:/usr/local/cuda-10.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/tsso_openssh/bin:/usr/local/sbin:/data/home/zhaodali/.ft:/data/home/zhaodali/.local/bin:/data/home/zhaodali/bin)
Including CUDA code.
/data6/zhaodali/Code/Trident-Dehazing-Network/DCNv2
Traceback (most recent call last):
  File "build.py", line 39, in <module>
    extra_compile_args=extra_compile_args
  File "/data4/zhaodali/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 292, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/data4/zhaodali/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/data4/zhaodali/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```

Do you have any suggestions?

**Comment by lj1995-computer-vision** [comment]
Try compiling https://github.com/jinfagang/DCNv2_latest.
